"""
Django settings for pondersec project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import mimetypes
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ImproperlyConfigured
import ssl

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

# Tokens de avaliação e cookies são assinados por esta chave. A chave real não
# pode ficar versionada; o fallback existe exclusivamente para desenvolvimento.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY é obrigatória quando DJANGO_DEBUG=False.')
    SECRET_KEY = 'django-insecure-local-development-only-change-me'

ALLOWED_HOSTS = ['10.208.200.20','localhost','pondersec.icomp.ufam.edu.br', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'responsegenerator',
]

try:
    import sslserver  # noqa: F401
except ImportError:
    pass
else:
    INSTALLED_APPS.append('sslserver')

CSRF_TRUSTED_ORIGINS = [
    'https://10.208.1.214',
    'http://10.208.1.214',
    'https://pondersec.icomp.ufam.edu.br',  # Já deixe pronto para quando o DNS funcionar!
    'http://pondersec.ufam.edu',
    'https://localhost',
    'http://localhost',
    'https://127.0.0.1',
    'http://127.0.0.1',
    'https://10.208.200.20',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Comprime páginas e JSON extensos quando não há Nginx na frente.
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes', 'on')

EMAIL_HOST_USER = os.environ.get('HOST_API_EMAIL') or os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('SENHA_API_EMAIL') or os.environ.get('EMAIL_HOST_PASSWORD')

# Diz para o backend de email do Django não validar estritamente o hostname
EMAIL_SSL_CONTEXT = ssl._create_unverified_context()
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'PonderSec <naoresp00@gmail.com>')

ROOT_URLCONF = 'pondersec.urls'

try:
    import whitenoise  # noqa: F401
except ImportError:
    pass
else:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'pondersec.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pondersec.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DB_ENGINE') == 'sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'pondersec_db'),
            'USER': os.environ.get('DB_USER', 'pondersec_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'teste123'),
            'HOST': os.environ.get('DB_HOST', 'db'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            # Reaproveita a conexão por thread entre requisições e valida uma
            # conexão reutilizada antes de entregá-la à aplicação. Ambos podem
            # ser desativados por ambiente sem alterar o backend de testes.
            'CONN_MAX_AGE': max(0, int(os.environ.get('DB_CONN_MAX_AGE', '60'))),
            'CONN_HEALTH_CHECKS': os.environ.get(
                'DB_CONN_HEALTH_CHECKS',
                'True',
            ).lower() in ('1', 'true', 'yes', 'on'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

LANGUAGES = [
    ('pt-br', _('Português')),
    ('en', _('English')),
    ('es', _('Español')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Os nomes versionados do collectstatic mudam a cada deploy, permitindo cache
# longo sem servir CSS ou imagens antigas depois de uma atualização.
WHITENOISE_MAX_AGE = 0 if DEBUG else 31536000
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/questoes/'
LOGOUT_REDIRECT_URL = '/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Limites externos explícitos evitam requests presos quando um provedor esgota cota
# ou deixa uma conexão aberta sem produzir conteúdo.
LLM_REQUEST_TIMEOUT_SECONDS = float(os.environ.get('LLM_REQUEST_TIMEOUT_SECONDS', '45'))
LLM_STREAM_TIMEOUT_SECONDS = float(os.environ.get('LLM_STREAM_TIMEOUT_SECONDS', '60'))
# Modelos diferentes da mesma pergunta podem responder em paralelo, mas o
# limite evita que uma configuração grande monopolize todas as threads.
LLM_MODELS_MAX_WORKERS = max(1, min(8, int(os.environ.get('LLM_MODELS_MAX_WORKERS', '4'))))
# A avaliação usa um pool separado para não atrasar novas respostas enquanto o
# JudgeAI processa resultados já exibidos ao usuário.
LLM_EVALUATION_MAX_WORKERS = max(1, min(8, int(os.environ.get('LLM_EVALUATION_MAX_WORKERS', '4'))))
LLM_CLIENT_CACHE_TTL_SECONDS = float(os.environ.get('LLM_CLIENT_CACHE_TTL_SECONDS', '300'))
LLM_CLIENT_CACHE_MAX_SIZE = int(os.environ.get('LLM_CLIENT_CACHE_MAX_SIZE', '8'))
LLM_PRELOAD_PROVIDER_SDKS = os.environ.get(
    'LLM_PRELOAD_PROVIDER_SDKS',
    'False',
).lower() in ('1', 'true', 'yes', 'on')
LLM_TRANSIENT_MAX_ATTEMPTS = int(os.environ.get('LLM_TRANSIENT_MAX_ATTEMPTS', '2'))
LLM_TRANSIENT_RETRY_DELAY_SECONDS = float(
    os.environ.get('LLM_TRANSIENT_RETRY_DELAY_SECONDS', '0.2')
)

# Protege as chaves dos provedores contra rajadas no chat anônimo. Em produção,
# use um cache compartilhado (Redis/Memcached) para um limite global entre workers.
PUBLIC_CHAT_RATE_LIMIT = max(1, int(os.environ.get('PUBLIC_CHAT_RATE_LIMIT', '30')))
PUBLIC_EVALUATION_RATE_LIMIT = max(1, int(os.environ.get('PUBLIC_EVALUATION_RATE_LIMIT', '120')))
PUBLIC_CHAT_RATE_WINDOW_SECONDS = max(
    1,
    int(os.environ.get('PUBLIC_CHAT_RATE_WINDOW_SECONDS', '60')),
)
PUBLIC_RATE_TRUST_X_REAL_IP = os.environ.get(
    'PUBLIC_RATE_TRUST_X_REAL_IP',
    'False',
).lower() in ('1', 'true', 'yes', 'on')
QUESTION_UPLOAD_MAX_BYTES = max(
    1,
    int(os.environ.get('QUESTION_UPLOAD_MAX_BYTES', str(10 * 1024 * 1024))),
)
QUESTION_UPLOAD_MAX_ITEMS = max(1, int(os.environ.get('QUESTION_UPLOAD_MAX_ITEMS', '20000')))

LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'pondersec': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'pondersec',
        },
    },
    'loggers': {
        'responsegenerator': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Força todos os links internos a usarem HTTPS
    SECURE_SSL_REDIRECT = True

    # Impede que os cookies de sessão e login sejam roubados em redes Wi-Fi públicas
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Proteção extra contra navegadores tentando "adivinhar" o tipo do arquivo
    SECURE_CONTENT_TYPE_NOSNIFF = True

mimetypes.add_type("text/css", ".css", True)
