# Generated by Django 5.2.12 on 2026-03-26 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
                ('descricao_categoria', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('quantitativa', 'Quantitativa'), ('qualitativa', 'Qualitativa')], max_length=20)),
                ('pontuacao_maxima', models.IntegerField(blank=True, null=True)),
                ('criterio_texto', models.TextField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliadores', to='responsegenerator.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.questao')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='questoes',
            field=models.ManyToManyField(blank=True, related_name='formularios', to='responsegenerator.questao'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_resposta', models.TextField()),
                ('llm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsegenerator.llm')),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='responsegenerator.questao')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_quali', models.TextField(blank=True, null=True)),
                ('avaliacao_quanti', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='responsegenerator.avaliador')),
                ('metrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.metrica')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsegenerator.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_quali', models.TextField(blank=True, null=True)),
                ('avaliacao_quanti', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.metrica')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsegenerator.resposta')),
            ],
        ),
    ]
