# Generated by Django 5.2.11 on 2026-03-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('quantitativa', 'Quantitativa'), ('qualitativa', 'Qualitativa')], max_length=20)),
                ('pontuacao_maxima', models.IntegerField(blank=True, null=True)),
                ('criterio_texto', models.TextField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
