# Generated by Django 5.2.12 on 2026-03-05 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0002_metrica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historico',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='resposta_gemini',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='resposta_groq',
        ),
        migrations.CreateModel(
            name='HistoricoAntigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta_gemini', models.TextField(blank=True, null=True)),
                ('resposta_groq', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.categoria')),
                ('llm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.llm')),
            ],
        ),
        migrations.AddField(
            model_name='historico',
            name='questao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.questao'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_resposta', models.TextField()),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsegenerator.llm')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsegenerator.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitativa', models.BooleanField(default=False)),
                ('avaliacao_quali', models.TextField(blank=True, null=True)),
                ('avaliacao_quanti', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsegenerator.resposta')),
            ],
        ),
    ]
