# Generated by Django 5.2.12 on 2026-03-05 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0003_categoria_llm_remove_historico_pergunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='quantitativa',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='metrica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.metrica'),
        ),
    ]
