# Generated by Django 5.2.12 on 2026-03-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0005_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao_categoria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
