# Generated by Django 5.2.13 on 2026-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0005_remove_formulario_criado_por_formulario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='label_opcao_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='metrica',
            name='label_opcao_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
