# Generated by Codex on 2026-05-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0006_metrica_label_opcao_1_metrica_label_opcao_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoJuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_quali', models.TextField(blank=True, null=True)),
                ('avaliacao_quanti', models.IntegerField(blank=True, null=True)),
                ('justificativa_geral', models.TextField(blank=True, null=True)),
                ('erro', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('juiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_como_juiz', to='responsegenerator.llm')),
                ('metrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.metrica')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_juizes', to='responsegenerator.resposta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
                'unique_together': {('usuario', 'juiz', 'resposta', 'metrica')},
            },
        ),
    ]
