# Generated by Django 5.2.12 on 2026-03-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0006_categoria_descricao_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='llm',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='questao',
        ),
        migrations.AddField(
            model_name='questao',
            name='respostas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.resposta'),
        ),
    ]
