# Generated by Django 5.2.12 on 2026-03-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0007_remove_resposta_llm_remove_resposta_questao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoAntigo',
        ),
    ]
