# Generated by Django 5.2.14 on 2026-06-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0007_avaliacaojuiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPonderSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=128)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin PonderSec',
                'verbose_name_plural': 'Admins PonderSec',
            },
        ),
        migrations.CreateModel(
            name='LLMPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llms_criadas', to='responsegenerator.adminpondersec')),
            ],
            options={
                'verbose_name': 'LLM Pública',
                'verbose_name_plural': 'LLMs Públicas',
                'ordering': ['-id'],
            },
        ),
    ]
