# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responsegenerator", "0008_adminpondersec_llmpublica"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerguntaPublica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conteudo", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pergunta Pública",
                "verbose_name_plural": "Perguntas Públicas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RespostaPublica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conteudo_resposta", models.TextField()),
                ("ok", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("llm", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="respostas_publicas", to="responsegenerator.llmpublica")),
                ("pergunta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="respostas", to="responsegenerator.perguntapublica")),
            ],
            options={
                "verbose_name": "Resposta Pública",
                "verbose_name_plural": "Respostas Públicas",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoPublicaLLM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("avaliacao_quali", models.TextField(blank=True, null=True)),
                ("avaliacao_quanti", models.IntegerField(blank=True, null=True)),
                ("justificativa_geral", models.TextField(blank=True, null=True)),
                ("erro", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("juiz", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="avaliacoes_publicas_como_juiz", to="responsegenerator.llmpublica")),
                ("metrica", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="responsegenerator.metrica")),
                ("resposta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="avaliacoes_cruzadas", to="responsegenerator.respostapublica")),
            ],
            options={
                "verbose_name": "Avaliação Pública por LLM",
                "verbose_name_plural": "Avaliações Públicas por LLM",
                "ordering": ["-atualizado_em"],
                "unique_together": {("juiz", "resposta", "metrica")},
            },
        ),
    ]
