# Generated by Django 5.2.11 on 2026-03-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0008_delete_historicoantigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='llm',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='respostas',
        ),
        migrations.AddField(
            model_name='resposta',
            name='llm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsegenerator.llm'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='responsegenerator.questao'),
        ),
    ]
