# Generated by Django 5.2.11 on 2026-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0009_remove_questao_llm_remove_questao_respostas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='possui_resposta',
            field=models.BooleanField(default=False),
        ),
    ]
