# Generated by Django 5.2.11 on 2026-03-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0010_questao_possui_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='possui_resposta',
        ),
    ]
