# Generated by Django 5.2.16 on 2026-07-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0010_questao_resposta_humana'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='tipo_respostas',
            field=models.CharField(choices=[('todas', 'Todas'), ('humana', 'Apenas Humana'), ('ia', 'Apenas IA'), ('ambas', 'IA + Humana')], default='todas', max_length=10),
        ),
    ]
