# Generated by Django 5.2.12 on 2026-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0011_remove_questao_possui_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='questoes',
            field=models.ManyToManyField(blank=True, related_name='formularios', to='responsegenerator.questao'),
        ),
    ]
