# Generated by Django 5.2.12 on 2026-03-26 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsegenerator', '0012_alter_formulario_questoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_quali', models.TextField(blank=True, null=True)),
                ('avaliacao_quanti', models.IntegerField(blank=True, null=True)),
                ('metrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsegenerator.metrica')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsegenerator.resposta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='responsegenerator.avaliador')),
            ],
        ),
    ]
