from django.urls import path
from . import views

urlpatterns = [
    path('menu/', views.menu, name="menu"),
    path('questoes/', views.questoes, name="questoes"),
    path('add_questoes/', views.add_questoes, name="add_questoes"),
    path('upload-perguntas/', views.upload_perguntas, name='upload_perguntas'),
    path('questoes-cadastro-categoria/', views.questoes_cadastro_categoria, name="questoes_cadastro_categoria"),
    path('menu_consulta/', views.menu_consulta, name="menu-consulta"),
    path('consulta_comparacao/', views.consulta_comparacao, name="consulta_comparacao"),
    path('executar_consulta', views.executar_consulta, name="executar_consulta"),
    path('avaliacao/', views.avaliacao, name="avaliacao"),
    path('avaliacao_respostas/', views.avaliacao_respostas, name="avaliacao_respostas"),
    path('setup-adicionar-metrica/', views.setup_adicionar_metrica, name='setup_adicionar_metrica'),
    #path('setup-adicionar-llm/', views.setup_adicionar_llm, name='setup_adicionar_llm'),
    path('setup-configurar-metrica/', views.setup_configurar_metrica, name='setup_configurar_metrica'),
    path('setup/', views.setup, name="setup"),
    path('setup_llm/', views.setup_llm, name="setup_llm"),
    path('setup_configurar_llm/', views.setup_configurar_llm, name="setup_configurar_llm"),
    path('setup_avaliacao/', views.setup_avaliacao, name="setup_avaliacao"),
    path('historico/', views.historico, name="historico"),
    path('historico/deletar/<int:id>/', views.deletar_item_historico, name='deletar_item_historico'),
    path('historico/ver/<int:id>/', views.ver_detalhes, name='ver_detalhes'),
    path('historico/limpar/', views.limpar_historico, name='limpar_historico'),
    path('avaliacao/adicionar/', views.avaliacao_adicionar_formulario, name="avaliacao_adicionar_formulario"),
    path('avaliacao/editar/<int:id>/', views.avaliacao_editar_formulario, name="avaliacao_editar_formulario"),
    path('avaliacao/deletar/<int:id>/', views.avaliacao_deletar_formulario, name="avaliacao_deletar_formulario"),
    path('upload-perguntas/', views.upload_perguntas ,name='upload_perguntas'),
    path("api/llm/<int:id>/delete/", views.deletar_llm, name="delete_llm"),
    path("api/llm/<int:id>/edit/", views.edit_llm_api),
    path("respostas/<int:questao_id>/", views.get_respostas, name="get_respostas"),
    #path('setup-deletar-metrica/<int:id>/', views.setup_deletar_metrica, name='setup_deletar_metrica'),
]
